@startuml
title Quiz States
[*] --> Unvalidated: [Quizmaster] Create Quiz
Unvalidated --> Running: [System] Validates if Quiz can be ran
Running --> Running: [Quizzer] Jumps
Running: Could be a real or practice quiz
Running --> Running: [Quizmaster] Record events
Running --> Completed: [Quizmaster] Completes
Completed --> Running: [Quizmaster] Resumes Quiz 
Completed --> Completed: [Quizmaster] Fix any errors from manually recording events
Completed --> Official: [System] Validates score, events and participation
Official: Only if a real, correct quiz
@enduml